"""
Data Models Module
Contains all data classes and enumerations used throughout the framework
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Dict, Any, Optional
from datetime import datetime


class SystemState(Enum):
    """System operational states"""
    IDLE = "idle"
    LISTENING = "listening"
    PROCESSING = "processing"
    RESPONDING = "responding"
    ERROR = "error"


@dataclass
class AudioFrame:
    """Represents a frame of audio data"""
    data: bytes
    sample_rate: int
    duration: float
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class TranscribedText:
    """Result of speech-to-text processing"""
    text: str
    confidence: float
    language: str = "en"
    duration: float = 0.0
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class Entity:
    """Named entity extracted from text"""
    name: str
    value: str
    entity_type: str
    confidence: float


@dataclass
class IntentResult:
    """Result of intent recognition"""
    intent: str
    confidence: float
    entities: List[Entity]
    raw_text: str
    processing_time: float = 0.0
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class DialogueResponse:
    """Response generated by the system"""
    text: str
    action: Optional[str] = None
    data: Dict[str, Any] = field(default_factory=dict)
    module: str = "core"
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class PerformanceMetric:
    """Performance metric for monitoring"""
    component: str
    metric_name: str
    value: float
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class ExternalSystemRequest:
    """Request to external system (hotel management, hospital records, etc.)"""
    system_name: str
    action: str
    data: Dict[str, Any]
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class ExternalSystemResponse:
    """Response from external system"""
    system_name: str
    status: str
    data: Dict[str, Any]
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
